---
name: cvmfs-client

director_uuid: <%= `bosh target lite > /dev/null 2>&1 && bosh status --uuid` %>

releases:
  - name: cvmfs-client
    version: latest

jobs:
  - name: cvmfs-client
    templates:
      - name: cvmfs-client
        release: cvmfs-client
    resource_pool: cvmfs-client
    networks:
      - name: cvmfs-client
    instances: 1

networks:
  - name: cvmfs-client
    subnets:
      - range: 10.244.16.0/24
        reserved: [10.244.16.1]
        static: []
        cloud_properties:
          name: random

resource_pools:
  - name: cvmfs-client
    network: cvmfs-client
    stemcell:
      name: bosh-warden-boshlite-ubuntu-trusty-go_agent
      version: latest
    cloud_properties:
      name: random

compilation:
  workers: 3
  network: cvmfs-client
  cloud_properties:
    name: random

update:
  canaries: 1
  max_in_flight: 3
  serial: false
  canary_watch_time: 1000-240000
  update_watch_time: 1000-240000
